#!/usr/bin/env bash
# Script that will display information about subdomains

# Function to fetch DNS information for a subdomain
DNS_info() {
    local subdomain="$1"
    local domain="$2"
    local ANSWER

    ANSWER=$(dig "$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $0}')
    echo "The subdomain $subdomain is a $(echo "$ANSWER" | awk '{print $4}') record and points to $(echo "$ANSWER" | awk '{print $5}')"
}

# Main script
if [[ $# == 1 ]]; then
    subdomains=('www' 'lb-01' 'web-01' 'web-02')
    for subdomain in "${subdomains[@]}"; do
        CONCAT="$subdomain.$1"
        DNS_info "$subdomain" "$CONCAT"
    done
elif [[ $# == 2 ]]; then
    CONCAT="$2.$1"
    DNS_info "$2" "$CONCAT"
else
    echo "Usage: $0 <domain> [<subdomain>]"
    exit 1
fi
